sudo: required
services:
  - docker

before_install:
  - docker build -t erickgallani/fibonacci-multi-docker-test-client -f ./client/Dockerfile.ci ./client

script:
  - docker run erickgallani/fibonacci-multi-docker-test npm run test -- --coverage

after_success:
  - docker build -t erickgallani/fibonacci-multi-docker-test-client ./client
  - docker build -t erickgallani/fibonacci-multi-docker-test-nginx ./nginx
  - docker build -t erickgallani/fibonacci-multi-docker-test-server ./server
  - docker build -t erickgallani/fibonacci-multi-docker-test-worker ./worker
  # Login to docker CI
  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
  # Push images to docker hub
  - docker push erickgallani/fibonacci-multi-docker-test-client
  - docker push erickgallani/fibonacci-multi-docker-test-nginx
  - docker push erickgallani/fibonacci-multi-docker-test-server
  - docker push erickgallani/fibonacci-multi-docker-test-worker